CREATE SCHEMA IF NOT EXISTS BAY;
CREATE TABLE IF NOT EXISTS BAY.USERS(
	ID				SERIAL PRIMARY KEY NOT NULL,
	FULL_NAME		TEXT NOT NULL,
	DATE_OF_BIRTH	TIMESTAMP,
	USERNAME		TEXT NOT NULL,
	PASSWORD		TEXT NOT NULL,
	EMAIL			TEXT NOT NULL,
	CREATED			TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);